model:
  posterior_kwargs:
    activation: gelu
    batch_norm: false
    context_with_glu: false
    dropout: 0.0
    hidden_dims:
    - 32
    - 64
    - 128
    - 256
    - 512
    - 1024
    - 1024
    - 1024
    - 512
    - 128
    - 64
    - 32
    sigma_min: 0.0001
    theta_with_glu: false
    time_prior_exponent: 4
    type: DenseResidualNet
  type: flow_matching
task:
  name: two_moons
  dim_theta: 2  # two_moons任务参数维度通常是2
  dim_x: 2 #同上
  num_train_samples: 3000
  num_rounds: 5
training:
  batch_size: 64
  early_stopping: true
  epochs: 100
  num_workers: 0
  optimizer:
    lr: 0.0002
    type: adam
  scheduler:
    factor: 0.2
    patience: 1
    type: reduce_on_plateau
  train_fraction: 0.95
sampling:
  n_samples_to_est_boundary: int(1e5)
  epsilon: 5e-4
